---
# vars file for ansible-role-terraform
base_arch:
  i386: '386'
  x86_64: 'amd64'
  amd64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm'

base_os:
  Linux: 'Linux-Unix'
  FreeBSD: 'Linux-Unix'
  OpenBSD: 'Linux-Unix'
  Solaris: 'Linux-Unix'
  Darwin: 'Linux-Unix'
  Win32NT: 'Windows'
