---
# vars file for terraform in Windows system
terraform_pkg_url: "https://releases.hashicorp.com/terraform/{{ terraform_version_to_install }}/terraform_{{ terraform_version_to_install }}_windows_{{ base_arch[ansible_architecture] | default('amd64') }}.zip"
terraform_default_path: C:\HashiCorp\terraform\bin\
os_type: windows
