---

# If we have any proxmox hosts, then use them to create the necessary VMs
- hosts: proxmox_servers:proxmox_vms
  gather_facts: no
  become: yes
  tasks: 

  # Setup Proxmox Terraform plugin locally
  - { import_role: { name: proxmox }, tags: [ proxmox, infrastructure ], become: no }


# VMWare usage #futureplans
# # If we have any vsphere hosts, then use them to create the necessary VMs
# - hosts: vcenter_servers:vsphere_vms
#   gather_facts: no
#   become: yes

#   tasks: 

#   # Setup Ansible Terraform plugin locally
#   - { import_role: { name: vsphere }, tags: [ vsphere, infrastructure ], become: no }
  
# If we have any k3s masters
- hosts: k3s_masters
  gather_facts: yes
  become: yes
  vars:
    orchestrator: kubernetes # this'll tell all roles that we're doing a kubernetes deploy

  tasks:

  # Setup K3s master
  - { import_role: { name: k3s-master }, tags: [ k3s-master ] }   

# If we have any k3s masters/workers, deploy them here
- hosts: k3s_masters:k3s_workers
  gather_facts: yes
  become: yes
  vars:
    orchestrator: kubernetes # this'll tell all roles that we're doing a kubernetes deploy

  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

  # Setup K3s worker
  - { import_role: { name: k3s-worker }, tags: [ k3s-worker ] }     

# configure gitlab
- hosts: git
  become: yes
  roles:
   - role: gitlab

# Deploy k3s Loadbalancer config
- hosts: localhost
  roles: 
   - role: k3spostconfig

