---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Terraform should be functionnal
      command: terraform --version
      register: terraform_result

    - name: Linux | Verify commands outputs
      assert:
        that:
          - terraform_result.rc == 0
        success_msg: "All tests passed"
      when: lookup('env', 'terraform_version') == "latest"

    - name: Linux | Verify commands outputs
      assert:
        that:
          - terraform_result.rc == 0
          - lookup('env', 'terraform_version') in terraform_result.stdout
        success_msg: "All tests passed"
      when: lookup('env', 'terraform_version') != "latest"
